#generate path
generate_unknown_filepath: "../dataset/train_unknown.csv"
generate_unknown_save_path: "./train_unknown.pt"

#dataset path
process_csv: 'train.csv'
process_unknown_csv: 'train_unknown.csv'
process_known_csv: 'train_known.csv'

#dataset_analyse path
analyse_read_csv: './train.csv'
processed_fil_1: 'processed_file.txt'
processed_fil_2: 'processed_file_2.txt'
processed_fil_3: 'processed_file_3.txt'
processed_fil_4: 'processed_file_4.txt'
log_analyse: 'log_analyse'
output_key:
  'output_key1.json'
  'output_key2.json'
  'output_key3.json'
  'output_key4.json'
  'output_key5.json'
  'output_key6.json'
  'output_key7.json'
  'output_key8.json'
  'output_key9.json'

#main
data_loader_path: "../data_generate/train_unknown.pt"
input_size: 10
lr1: 0.0001
num_epochs: 100

#model
lr2: 0.001

#tool
batch_size: 512
load_data: "../data_generate/train_unknown.pt"