# work_dir is NewUserPredict which has been defined at python code
# generate path
train_csv: 'dataset/train.csv'

train_unknown_csv: "dataset/train_unknown.csv"
train_unknown_pt: "data_generate/train_unknown.pt"

train_known_csv: 'dataset/train_known.csv'
train_known_pt: "data_generate/train_known.pt"

model_save_path: "model/"
plt_save_path: "photo/"


# train
input_size: 12
hidden_size1: 64
hidden_size2: 32
lr: 0.01
division_rate: 0.8
num_epochs: 90
batch_size: 512